/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './ng2-restangular.module';
import * as import2 from './ng2-restangular';
import * as import3 from '@angular/core/src/di/injector';
import * as import4 from './ng2-restangular.config';
import * as import5 from './ng2-restangular-http';
class RestangularModuleInjector extends import0.NgModuleInjector<import1.RestangularModule> {
  _RestangularModule_0:import1.RestangularModule;
  __Restangular_1:import2.Restangular;
  constructor(parent:import3.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _Restangular_1():import2.Restangular {
    if ((this.__Restangular_1 == null)) { (this.__Restangular_1 = new import2.Restangular(this.parent.get(import4.RESTANGULAR,(null as any)),this,this.parent.get(import5.RestangularHttp))); }
    return this.__Restangular_1;
  }
  createInternal():import1.RestangularModule {
    this._RestangularModule_0 = new import1.RestangularModule(this.parent.get(import1.RestangularModule,(null as any)));
    return this._RestangularModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.RestangularModule)) { return this._RestangularModule_0; }
    if ((token === import2.Restangular)) { return this._Restangular_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const RestangularModuleNgFactory:import0.NgModuleFactory<import1.RestangularModule> = new import0.NgModuleFactory(RestangularModuleInjector,import1.RestangularModule);